### ISSUE TITLE
rl_callback_read_char

### ISSUE THREAD

**Issue by EranGoldman** [ramok/sdmsh#2]
Hi again ,

Now when I'm running the make I get : 

{{{
$ make
cc -lreadline -W -Wall -I. -lm -ggdb -DLOGGER_ENABLED   -c -o sdmsh.o sdmsh.c
cc -lreadline -W -Wall -I. -lm -ggdb -DLOGGER_ENABLED   -c -o sdm.o sdm.c
cc -lreadline -W -Wall -I. -lm -ggdb -DLOGGER_ENABLED   -c -o shell.o shell.c
cc -lreadline -W -Wall -I. -lm -ggdb -DLOGGER_ENABLED   -c -o commands.o commands.c
cc -lreadline -W -Wall -I. -lm -ggdb -DLOGGER_ENABLED   -c -o logger.o logger.c
cc -lreadline -W -Wall -I. -lm -ggdb -DLOGGER_ENABLED -o sdmsh sdmsh.o sdm.o shell.o commands.o logger.o
sdmsh.o: In function `main':
/home/marinetech/projects/sdmsh/sdmsh.c:116: undefined reference to `rl_callback_read_char'
/home/marinetech/projects/sdmsh/sdmsh.c:134: undefined reference to `rl_forced_update_display'
sdm.o: In function `smd_rcv_idle_state':
/home/marinetech/projects/sdmsh/sdm.c:356: undefined reference to `rl_clear_message'
shell.o: In function `rl_cb_getline':
/home/marinetech/projects/sdmsh/shell.c:28: undefined reference to `add_history'
shell.o: In function `shell_cb_completion':
/home/marinetech/projects/sdmsh/shell.c:69: undefined reference to `rl_completion_matches'
/home/marinetech/projects/sdmsh/shell.c:70: undefined reference to `rl_line_buffer'
/home/marinetech/projects/sdmsh/shell.c:71: undefined reference to `rl_completion_suppress_append'
/home/marinetech/projects/sdmsh/shell.c:72: undefined reference to `rl_completion_matches'
/home/marinetech/projects/sdmsh/shell.c:73: undefined reference to `rl_line_buffer'
/home/marinetech/projects/sdmsh/shell.c:74: undefined reference to `rl_line_buffer'
/home/marinetech/projects/sdmsh/shell.c:75: undefined reference to `rl_filename_completion_function'
/home/marinetech/projects/sdmsh/shell.c:75: undefined reference to `rl_completion_matches'
/home/marinetech/projects/sdmsh/shell.c:76: undefined reference to `rl_completion_suppress_append'
/home/marinetech/projects/sdmsh/shell.c:77: undefined reference to `rl_filename_completion_desired'
shell.o: In function `shell_init':
/home/marinetech/projects/sdmsh/shell.c:94: undefined reference to `read_history'
/home/marinetech/projects/sdmsh/shell.c:96: undefined reference to `rl_callback_handler_install'
/home/marinetech/projects/sdmsh/shell.c:99: undefined reference to `rl_readline_name'
/home/marinetech/projects/sdmsh/shell.c:100: undefined reference to `rl_attempted_completion_function'
/home/marinetech/projects/sdmsh/shell.c:101: undefined reference to `rl_completion_entry_function'
shell.o: In function `shell_deinit':
/home/marinetech/projects/sdmsh/shell.c:107: undefined reference to `write_history'
/home/marinetech/projects/sdmsh/shell.c:112: undefined reference to `rl_callback_handler_remove'
shell.o: In function `shell_run_cmd':
/home/marinetech/projects/sdmsh/shell.c:166: undefined reference to `rl_forced_update_display'
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1
}}}

Do I need to install any thing else ?

Thanks

**Comment by ramok** [comment]
Looks like cc find readline .h files, but linker do not find readline .so or .a files.
Errors shot that linker cannot find readline functions.

How you install readline library?
You need find where in your system located libreadline.so.*

**Comment by EranGoldman** [comment]
solved.
I moved the flags to the end of the cc line

**Comment by ramok** [comment]
good. i'm fix it in my repo. thanks for report :)

**Comment by ramok** [comment]
my bad. just see your pull request
